export const CATEGORIES = [
  { id: "immobilier", label: "Immobilier", icon: "🏠" },
  { id: "vehicules_transport", label: "Véhicules", icon: "🚗" },
  { id: "emploi_services", label: "Emploi & services", icon: "💼" },
  { id: "electronique", label: "Électronique", icon: "📱" },
  { id: "maison_jardin", label: "Maison & jardin", icon: "🛋️" },
  { id: "discussion", label: "Discussions", icon: "💬" },
];

export const LISTINGS = [
  {
    id: "1",
    title: "Appartement moderne 2 chambres",
    price: "800 $ / mois",
    location: "Gombe, Kinshasa",
    time: "Il y a 2 h",
    category: "immobilier",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop",
    tags: ["2 chambres", "2 salles de bain", "Salon", "Parking"],
    description:
      "Bel appartement lumineux au cœur de Gombe, proche des ambassades. Cuisine équipée, balcon avec vue. Idéal pour expatriés ou famille.",
    photos: 8,
    phone: "+243 900 000 001",
  },
  {
    id: "2",
    title: "Studio meublé Limete",
    price: "450 $ / mois",
    location: "Limete, Kinshasa",
    time: "Il y a 5 h",
    category: "immobilier",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop",
    tags: ["1 chambre", "Meublé", "Sécurité"],
    description: "Studio entièrement meublé, eau et électricité comprises. Quartier calme, accès facile.",
    photos: 5,
    phone: "+243 900 000 002",
  },
  {
    id: "3",
    title: "Villa 4 chambres avec jardin",
    price: "2 500 $ / mois",
    location: "Binza, Kinshasa",
    time: "Hier",
    category: "immobilier",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop",
    tags: ["4 chambres", "Jardin", "Garage"],
    description: "Grande villa familiale avec jardin et garage double. Quartier résidentiel prisé.",
    photos: 12,
    phone: "+243 900 000 003",
  },
  {
    id: "4",
    title: "iPhone 13 Pro — état neuf",
    price: "650 $",
    location: "Gombe, Kinshasa",
    time: "Il y a 1 j",
    category: "electronique",
    image: "https://images.unsplash.com/photo-1632661678646-df8346ee3b8?w=400&h=300&fit=crop",
    tags: ["128 Go", "Débloqué", "Facture"],
    description: "iPhone 13 Pro en excellent état, boîte et accessoires inclus.",
    photos: 4,
    phone: "+243 900 000 004",
  },
  {
    id: "5",
    title: "Chauffeur expérimenté disponible",
    price: "Sur devis",
    location: "Kinshasa",
    time: "Il y a 3 h",
    category: "vehicules_transport",
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400&h=300&fit=crop",
    tags: ["Permis B", "10 ans d'expérience"],
    description: "Chauffeur professionnel, connaissance de Kinshasa, disponible à temps plein ou partiel.",
    photos: 1,
    phone: "+243 900 000 005",
  },
];

export const DISCUSSIONS = [
  {
    id: "d1",
    title: "Meilleur quartier pour vivre à Kin ?",
    category: "immobilier",
    replies: 24,
    time: "Il y a 2 h",
    author: "Sarah K.",
    avatar: "SK",
    body: "Je déménage à Kinshasa le mois prochain. Gombe, Limete, Binza — vos avis ?",
    thread: [
      { author: "Michel B.", avatar: "MB", time: "Il y a 1 h", text: "Gombe si budget permet, sinon Limete est très pratique." },
      { author: "Amina T.", avatar: "AT", time: "Il y a 45 min", text: "Binza pour les familles, plus calme et vert." },
    ],
  },
  {
    id: "d2",
    title: "Starlink en RDC, vos avis ?",
    category: "electronique",
    replies: 56,
    time: "Il y a 5 h",
    author: "John D.",
    avatar: "JD",
    body: "Quelqu'un utilise Starlink à Kinshasa ? La latence et le prix en valent-ils ?",
    thread: [
      { author: "Paul R.", avatar: "PR", time: "Il y a 3 h", text: "Très stable pour le télétravail, un peu cher au début." },
    ],
  },
  {
    id: "d3",
    title: "Comment trouver un bon plombier ?",
    category: "emploi_services",
    replies: 12,
    time: "Hier",
    author: "Marie L.",
    avatar: "ML",
    body: "Fuite dans la salle de bain — recommandations fiables à Kinshasa ?",
    thread: [],
  },
];

export const USER = {
  name: "Jonathan M.",
  since: "Membre depuis janv. 2025",
  avatar: "JM",
};
