export const CATEGORIES = [
  { id: "immobilier", label: "Appartements à louer", icon: "⌂" },
  { id: "vehicules_transport", label: "Véhicules", icon: "🚗" },
  { id: "emploi_services", label: "Emplois", icon: "▣" },
  { id: "electronique", label: "Électroniques", icon: "▯" },
  { id: "maison_jardin", label: "Services", icon: "⌘" },
  { id: "discussion", label: "Discussions", icon: "💬" },
];

export const LISTINGS = [
  {
    id: "1",
    title: "Appartement moderne 2 chambres",
    price: "800 $ / mois",
    location: "Gombe",
    time: "2h",
    category: "immobilier",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop",
    ],
    tags: ["2 chambres", "2 salles de bain", "Salon", "Parking"],
    description:
      "Bel appartement moderne et lumineux à louer à Gombe. 2 chambres, salon spacieux, cuisine équipée, balcon avec belle vue, parking disponible, sécurité 24h/24.",
    whatsapp: "+243 900 000 001",
    viewCount: 124,
    likeCount: 7,
  },
  {
    id: "2",
    title: "Studio meublé à louer Gombe",
    price: "400 $ / mois",
    location: "Gombe",
    time: "4h",
    category: "immobilier",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop",
    ],
    tags: ["1 chambre", "Meublé", "Sécurité"],
    description: "Studio entièrement meublé, eau et électricité comprises. Quartier calme à Gombe, accès facile.",
    whatsapp: "+243 900 000 002",
    viewCount: 58,
    likeCount: 3,
  },
  {
    id: "3",
    title: "Appartement 3 chambres avec balcon, Gombe",
    price: "1 200 $ / mois",
    location: "Gombe",
    time: "6h",
    category: "immobilier",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop",
    ],
    tags: ["3 chambres", "Balcon", "Parking"],
    description: "Appartement spacieux avec balcon, salon lumineux et parking sécurisé.",
    whatsapp: "+243 900 000 003",
  },
  {
    id: "6",
    title: "Chambre à louer, Gombe",
    price: "150 $ / mois",
    location: "Gombe",
    time: "8h",
    category: "immobilier",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=400&h=300&fit=crop",
    ],
    tags: ["Chambre", "Cuisine partagée"],
    description: "Chambre propre et sécurisée à louer à Gombe, proche des commerces.",
    whatsapp: "+243 900 000 006",
  },
  {
    id: "8",
    title: "Je cherche un appartement 2 chambres à Gombe",
    price: "Budget 600 $ / mois",
    location: "Gombe",
    time: "1h",
    category: "immobilier",
    intent: "demande",
    images: [],
    tags: ["2 chambres", "Parking", "Sécurité"],
    description:
      "Famille cherche appartement lumineux à Gombe, 2 chambres minimum, parking souhaité. Disponible dès juillet.",
    whatsapp: "+243 900 000 008",
  },
  {
    id: "4",
    title: "iPhone 13 Pro — état neuf",
    price: "650 $",
    location: "Gombe, Kinshasa",
    time: "Il y a 1 j",
    category: "electronique",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1632661678646-df8346ee3b8?w=400&h=300&fit=crop",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=300&fit=crop",
    ],
    tags: ["128 Go", "Débloqué", "Facture"],
    description: "iPhone 13 Pro en excellent état, boîte et accessoires inclus.",
    whatsapp: "+243 900 000 004",
  },
  {
    id: "5",
    title: "Chauffeur expérimenté disponible",
    price: "Sur devis",
    location: "Kinshasa",
    time: "Il y a 3 h",
    category: "vehicules_transport",
    intent: "offre",
    images: [
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400&h=300&fit=crop",
    ],
    tags: ["Permis B", "10 ans d'expérience"],
    description: "Chauffeur professionnel, connaissance de Kinshasa, disponible à temps plein ou partiel.",
    whatsapp: "+243 900 000 005",
  },
  {
    id: "7",
    title: "Comptable — recherche emploi à Kinshasa",
    price: "Sur entente",
    location: "Gombe",
    time: "Il y a 1 h",
    category: "emploi_services",
    intent: "demande",
    images: [],
    resumeUrl: null,
    tags: ["5 ans d'expérience", "Sage", "Bilingue"],
    description:
      "Comptable diplômé avec 5 ans d'expérience en PME. Disponible immédiatement, références sur demande via WhatsApp.",
    whatsapp: "+243 900 000 007",
  },
];

export const DISCUSSIONS = [
  {
    id: "d1",
    title: "Meilleur quartier pour vivre à Kin ?",
    category: "immobilier",
    replies: 24,
    time: "Il y a 2 h",
    author: "Sarah K.",
    avatar: "SK",
    body: "Je déménage à Kinshasa le mois prochain. Gombe, Limete, Binza — vos avis ?",
    thread: [
      { author: "Michel B.", avatar: "MB", time: "Il y a 1 h", text: "Gombe si budget permet, sinon Limete est très pratique." },
      { author: "Amina T.", avatar: "AT", time: "Il y a 45 min", text: "Binza pour les familles, plus calme et vert." },
    ],
  },
  {
    id: "d2",
    title: "Starlink en RDC, vos avis ?",
    category: "electronique",
    replies: 56,
    time: "Il y a 5 h",
    author: "John D.",
    avatar: "JD",
    body: "Quelqu'un utilise Starlink à Kinshasa ? La latence et le prix en valent-ils ?",
    thread: [
      { author: "Paul R.", avatar: "PR", time: "Il y a 3 h", text: "Très stable pour le télétravail, un peu cher au début." },
    ],
  },
  {
    id: "d3",
    title: "Comment trouver un bon plombier ?",
    category: "emploi_services",
    replies: 12,
    time: "Hier",
    author: "Marie L.",
    avatar: "ML",
    body: "Fuite dans la salle de bain — recommandations fiables à Kinshasa ?",
    thread: [],
  },
];

export const USER = {
  name: "Jonathan M.",
  since: "Membre depuis janv. 2025",
  avatar: "JM",
  whatsapp: "",
};
